// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgfqyjbsrubynkxhpdpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnZnF5amJzcnVieW5reGhwZHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Mzg4NjUsImV4cCI6MjA2ODIxNDg2NX0.P9jbKgWmWBLxbS4_UbhTGxWHQiMi21pOnC5bRXXhi-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);